### ISSUE TITLE
🔖 Roadmap for v1

### ISSUE THREAD

**Issue by lzm0x219** [lzm0x219/vscode-markdown-github#2]
## 🔖 Roadmap for v1

In the v1 plan, we will focus on completing a complete reproduction of the github markdown style, including support for the dark theme. And support users to manually switch the theme.

### Tasks
- Github themes (light & dark)
  - [ ] Headings
  - [ ] Styling text
  - [ ] Bold
  - [ ] Italic
  - [ ] Strike through
  - [ ] Bold and nested italic
  - [ ] All bold and italic
  - [ ] Subscript
  - [ ] Superscript
  - [ ] Paragraphs
  - [ ] Quoting text
  - [ ] Quoting code
  - [ ] Supported color models
  - [ ] Links
  - [ ] Section links
  - [ ] Images
  - [ ] Lists
  - [ ] Task lists
  - [ ] Using emoji
  - [ ] Footnotes
  - [ ] Table
  - [ ] Collapsed section
- Theme
   - [ ] Switch theme
   - [ ] Automatically adapt to the theme
- Multi-language Support
  - [ ] TODO
