### ISSUE TITLE
Task lists

### ISSUE THREAD

**Issue by lzm0x219** [lzm0x219/vscode-markdown-github#21]
## Task lists

To create a task list, preface list items with a hyphen and space followed by [ ]. To mark a task as complete, use [x].

### Expected effect:

Example:
```md
- [x] #10
- [ ] https://github.com/lzm0x219/vscode-markdown-github/issues/10
- [ ] Add delight to the experience when all tasks are complete :tada:
```

Output:

- [x] #10
- [ ] https://github.com/lzm0x219/vscode-markdown-github/issues/10
- [ ] Add delight to the experience when all tasks are complete :tada:

If a task list item description begins with a parenthesis, you'll need to escape it with \:
```
- [ ] \(Optional) Open a followup issue
```

### TODO
Associate github's issue and pr.

### Reference
[Task lists](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#task-lists)
